Added TestStyle to CommandCards
radikris/booking_calendar pull request #33
Opened 2022-12-18 11:27 UTC by mazenhalawi

I added TestStyle to the CommandCard text to enable the developer to use other background colors that won't interfere with the text. Also, the text is quite small so using TextStyle the developer is free to style the text the way he wants with Size, Weight, Color...

2022-12-18 11:32 UTC, radikris requested changes
Thank you very much for your contribution!
If you solve my comment regarding to the iOS config changes, I will approve your pull request, thanks again!

2022-12-18 11:32 UTC, radikris commented on example/ios/Flutter/AppFrameworkInfo.plist
> -  <string>9.0</string>
I don't think these iOS config editings are neccessary for the pull request, please remove from the changes

2022-12-18 13:21 UTC, mazenhalawi commented on example/ios/Flutter/AppFrameworkInfo.plist
> -  <string>9.0</string>
Sorry I didnt realize those files changed. I just reverted the ios folder in the example to the way it was before my changes.

2022-12-19 20:50 UTC, mazenhalawi commented on example/ios/Flutter/AppFrameworkInfo.plist
> -  <string>9.0</string>
hey @radikris, did you check the changes I made?

2022-12-28 17:35 UTC, mazenhalawi commented
hello @radikris, its been a while, do you think you can push those changes so i can use the features i have implemented please?

2023-01-02 08:09 UTC, radikris commented
@mazenhalawi Hi, sorry for my delay, I am back, and alright, it's merged

2023-01-02 08:09 UTC, merged